spring:
  redis:
    host: ${REDIS_HOST:172.16.1.224}
    port: ${REDIS_PORT:21600}
    password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 0
thread:
  count: ${ThreadCount:16}
###############################---阿里云---##############################
aliyun:
  endpoint: https://oss-cn-beijing.aliyuncs.com/
  accessKeyId: LTAIUEAyF5F1rtjD
  accessKeySecret: 6E4HR2AI8Bwd9DlfcjcwjksjFfpkzD
  bucketName: dmp-phone-md5